
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_elt_testing'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt-snowflake-db'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

vars:
  odate: '2021-03-25'
  default_null_variable: 0
  target_schema: DBT_POC_HCL_SCHEMA
  stg_schema: DBT_POC_ETL_DB
  db_name: DBT_POC_HCL_DB
  time_zone: "America/Chicago"
##
##on-run-start:
  ##- "create table if not exists dbt_stg.load_audit( model_name string, model_state string, model_exe_time timestamp_ltz)"

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_elt_testing:
      # Applies to all files under models/example/
      staging:
        pre-hook: "BEGIN TRANSACTION"
        post-hook: "COMMIT"
